---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: filebeat
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2004}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/converge.yml
    verify: ../common/verify.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    group_vars:
      all:
        elastic_repo_major_version: "{{ lookup('env','MOLECULE_ELASTIC_MAJOR_VERSION') }}"
        filebeat_package_hold: true
        filebeat_conf_extra:
          logging:
            level: info
            to_files: true
            files:
              path: /var/log
              name: filebeat
              keepfiles: 7
              permissions: "0640"
        filebeat_conf_inputs:
          - type: filestream
            id: syslog
            paths:
              - /var/log/syslog
              - /var/log/messages
          - type: journald
            id: journald
        filebeat_conf_output:
          file:
            path: /tmp
            filename: filebeat
verifier:
  name: ansible
