---
filebeat_repo_manage: true
filebeat_package_names: filebeat
filebeat_package_state: present
filebeat_conf_manage: true
filebeat_conf_path: /etc/filebeat/filebeat.yml
filebeat_conf_modules_path: /etc/filebeat/modules.d
filebeat_service_name: filebeat
filebeat_service_status: started
filebeat_service_enabled: true
filebeat_package_hold: false

filebeat_conf_elasticsearch_enabled: true
filebeat_conf_elasticsearch_loadbalance: true
filebeat_conf_elasticsearch_port: 9200
filebeat_conf_elasticsearch_hosts: ['localhost']

filebeat_conf_logstash_enabled: false
filebeat_conf_logstash_loadbalance: true
filebeat_conf_logstash_port: 5044
filebeat_conf_logstash_hosts: ['localhost']

filebeat_conf_dashboards_enabled: false
filebeat_conf_dashboards_kibana: true
filebeat_conf_template_enabled: true
filebeat_conf_kibana_host: 'localhost:80'

filebeat_conf_modules: []
filebeat_conf_inputs: []

filebeat_conf_extra: {}

_filebeat_conf_port_elasticsearch: "{{ filebeat_conf_elasticsearch_port }}:"
_filebeat_conf_port_logstash: "{{ filebeat_conf_logstash_port }}:"

filebeat_conf_output_elasticsearch:
  enabled: "{{ filebeat_conf_elasticsearch_enabled }}"
  hosts: "{{ filebeat_conf_elasticsearch_hosts | product([_filebeat_conf_port_elasticsearch]) | map('join') | list }}"
  loadbalance: "{{ filebeat_conf_elasticsearch_loadbalance }}"

filebeat_conf_output_logstash:
  enabled: "{{ filebeat_conf_logstash_enabled }}"
  hosts: "{{ filebeat_conf_elasticsearch_hosts | product([_filebeat_conf_port_logstash]) | map('join') | list }}"
  loadbalance: "{{ filebeat_conf_logstash_loadbalance }}"

filebeat_conf_output:
  elasticsearch: "{{ filebeat_conf_output_elasticsearch }}"
  logstash: "{{ filebeat_conf_output_logstash }}"

filebeat_conf_setup:
  dashboards:
    enabled: "{{ filebeat_conf_dashboards_enabled }}"
    beat: filebeat
    always_kibana: "{{ filebeat_conf_dashboards_kibana }}"
  template:
    enabled: "{{ filebeat_conf_template_enabled }}"
  kibana:
    host: "{{ filebeat_conf_kibana_host }}"

filebeat_conf_base:
  filebeat:
    config:
      modules:
        path: "{{ filebeat_conf_modules_path }}/*.yml"
    inputs: "{{ filebeat_conf_inputs }}"
  output: "{{ filebeat_conf_output }}"
  setup: "{{ filebeat_conf_setup }}"

filebeat_conf: "{{ filebeat_conf_base | combine(filebeat_conf_extra) }}"
