---
filebeat_repo_manage: true
filebeat_package_names: filebeat
filebeat_package_state: present
filebeat_conf_manage: true
filebeat_conf_path: /etc/filebeat/filebeat.yml
filebeat_conf_modules_path: /etc/filebeat/modules.d
filebeat_service_name: filebeat
filebeat_service_status: started
filebeat_service_enabled: true
filebeat_package_hold: false

filebeat_conf_modules: []
filebeat_conf_inputs: []

filebeat_conf_output:
  enabled: true
  hosts: "localhost:9201"
  loadbalance: false

filebeat_conf_setup:
  dashboards:
    enabled: false
  template:
    enabled: false
  ilm:
    enabled: false

filebeat_conf_logging:
  level: warning
  to_syslog: false
  to_files: true
  files:
    path: /var/log/filebeat
    name: filebeat
    keepfiles: 7
    permissions: "0644"

filebeat_conf_seccomp:
  enabled: false

filebeat_conf_fields: {}

filebeat_conf:
  filebeat:
    inputs: "{{ filebeat_conf_inputs }}"
    config:
      modules:
        path: "{{ filebeat_conf_modules_path }}/*.yml"
  output: "{{ filebeat_conf_output }}"
  setup: "{{ filebeat_conf_setup }}"
  logging: "{{ filebeat_conf_logging }}"
  seccomp: "{{ filebeat_conf_seccomp }}"
  fields: "{{ filebeat_conf_fields }}"
