---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-${MOLECULE_DISTRO:-ubuntu2204}-ansible
    pre_build_image: true
    command: ${MOLECULE_COMMAND:-"/lib/systemd/systemd"}
    cgroupns_mode: host
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  log: true
  playbooks:
    converge: ${MOLECULE_PLAYBOOK:-converge.yml}
  inventory:
    group_vars:
      all:
        filebeat_conf_modules:
          - module: system
        filebeat_conf_inputs:
          - type: log
            paths:
              - /var/log/messages
scenario:
  name: default
verifier:
  name: ansible
