---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: filebeat
    image: "geerlingguy/docker-${MOLECULE_DOCKER_IMAGE:-ubuntu2404}-ansible:latest"
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    cgroupns_mode: host
    privileged: true
    pre_build_image: true
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /tmp
      - /opt
provisioner:
  name: ansible
  log: true
  playbooks:
    prepare: ../common/prepare.yml
    converge: ../common/converge.yml
    verify: ../common/verify.yml
  config_options:
    defaults:
      callbacks_enabled: ansible.posix.profile_tasks
  inventory:
    group_vars:
      all:
        elastic_repo_major_version: "{{ lookup('env','MOLECULE_BEATS_MAJOR_VERSION', default=9) }}"
        filebeat_package_hold: true
        filebeat_conf_logging:
          files:
            keepfiles: 7
            name: filebeat
            path: /var/log/filebeat
            permissions: "0644"
          level: info
          to_files: true
          to_syslog: false
        filebeat_conf_inputs:
          - type: filestream
            id: molecule
            enabled: true
            paths:
              - /tmp/test.log
            prospector:
              scanner:
                fingerprint:
                  enabled: false
        filebeat_conf_output:
          file:
            path: /tmp
            filename: filebeat
verifier:
  name: ansible
