---
- name: Verify

  hosts: all

  tasks:

    - name: query service facts
      ansible.builtin.service_facts:

    - name: ensure filebeat service is running
      ansible.builtin.fail:
        msg: "filebeat service is not running"
      when: ansible_facts.services['filebeat'].state != 'running'
