---
name: release

env:
  DEVBOX_VERSION: ${{ vars.DEVBOX_VERSION }}

on:
  push:
    tags:
      - "*"

defaults:
  run:
    working-directory: "nephelaiio.filebeat"

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: "nephelaiio.filebeat"

      - name: Generate devbox locale
        run: sudo locale-gen C.UTF-8

      - name: Install devbox
        uses: jetify-com/devbox-install-action@v0.13.0
        with:
          enable-cache: true

      - name: Install dependencies
        run: make install

      - name: Release collection
        run: devbox run -- make publish
        env:
          GALAXY_API_KEY: "${{ secrets.GALAXY_API_KEY }}"
          GITHUB_REPOSITORY: "${{ github.repository }}"
